[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chat-api"
version = "0.1.0"
description = "Shared Chat API"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["chat_api"]
